name: Go
on: [push]
jobs:

  build:
    strategy:
      matrix:
        go_version: ["1.10", "1.11", "1.12"]

    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go_version }}
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
    - name: Checkout submodules
      run: git submodule update --init

    - name: Build
      run: 
        | go get
        | go test
